### ISSUE TITLE
we're using this in crocodilejs

### ISSUE THREAD

**Issue by niftylettuce** [yawetse/formie#1]
hey just wanted to say thanks for putting this together, I was going to use https://github.com/malsup/form/ but I really like that you built on top of superagent.

using this at https://github.com/crocodilejs/crocodile-node-mvc-framework

v1.0.0 coming out soon!

**Comment by yawetse** [comment]
Thanks! I want to refactor it at some point from super agent to using
what-wg fetch!

**Comment by niftylettuce** [comment]
@yawetse we could use my https://github.com/crocodilejs/frisbee which uses WHATWG fetch and is similar to superagent in API style.

**Comment by yawetse** [comment]
very interesting. btw I like what you're doing with crocodile, it's similar to what periodicjs does. I have a similar react native (boilerplate/framework) that does a similar thing in a client application context to crocodile and periodic. Im going to release in a couple of weeks.
